### ISSUE TITLE
Run hlint as part of a test-suite

### ISSUE THREAD

**Issue by vu3rdd** [bangalore-haskell-user-group/functorrent#14]

**Comment by vu3rdd** [comment]
The travis test fails because one of the dependency (haskell-src-exts-1.16.0.1) didn't install.  The same package installed fine on my machine. I have no idea how to move forward with this.

**Comment by vu3rdd** [comment]
Fixed the travis build issue, by adding the happy installation in travis.yml file. @jaseemabid @dfordivam comments?

**Comment by jaseemabid** [comment]
Seems like an issue with GHC 7.8, which is enforced because I put it in the `.travis.yml`file. I dont think we need to be compatible with older versions of GHC. So I'm fine with this fix. Maybe the next stackage lts will include fixed libraries, so we can remove the additional config then.

LGTM.

**Comment by vu3rdd** [comment]
Merged. 

FYI: I used the branch naming <issue-#>-description-iteration. eg: 14-hlint-testsuite-0, may be next iteration after review comments could be 14-hlint-testsuite-1 etc. Feel free to use any branch naming.
