### ISSUE TITLE
Should we checkin cabal.config?

### ISSUE THREAD

**Issue by vu3rdd** [bangalore-haskell-user-group/functorrent#16]
According to [this article on stackage](http://www.yesodweb.com/blog/2014/11/cabal-sandbox-stackage), we can checkin the generated cabal.config so that others can reproduce the exact build setup along with dependencies.

Does anyone see any reason why it shouldn't be checked in?

**Comment by jaseemabid** [comment]
@vu3rdd I did think of the same. Since we refer to lts, and a new lts release is not a _very_ frequent thing, we should be fine either way.

**Comment by jaseemabid** [comment]
@vu3rdd Lets check in. This will ensure travis/any CI will build the same thing as local. We can update the file per LTS release.

**Comment by jaseemabid** [comment]
Fixed at https://github.com/vu3rdd/functorrent/pull/30
