### ISSUE TITLE
Tests with tasty 

### ISSUE THREAD

**Issue by jaseemabid** [bangalore-haskell-user-group/functorrent#9]
Managed to add some tests to my own lisper, will try to do some same for
functorrent next weekend or so.

Hunit is a mess, and had a really bad time with it. It would always report a
success and count to be 1. Thankfully Tasty feels really good. Got the whole
thing hooked up with travis-ci so the builds are available publicly[2].

See the last few commits[1] for details. One of the main things to do was to
split the project into a library and an executable.

Give it a try! 
1. https://github.com/jaseemabid/lisper/commits/master
2. https://travis-ci.org/jaseemabid/lisper

**Comment by jaseemabid** [comment]
This should help http://jaspervdj.be/posts/2015-03-13-practical-testing-in-haskell.html

**Comment by dfordivam** [comment]
ok we can start with tasty. Can you commit a set of initial files required for this.
Also I think we should pick some basic test-cases from the existing torrent test-suite.
Here is a link to [libtorrent's test-suite](https://github.com/libtorrent/libtorrent/tree/master/test)

**Comment by dfordivam** [comment]
I just realised that we are already creating test-cases from libtorrent

**Comment by jaseemabid** [comment]
Are we?

**Comment by dfordivam** [comment]
well the doctests are taken from https://github.com/libtorrent/libtorrent/blob/master/test/test_bencoding.cpp

**Comment by jaseemabid** [comment]
I'm not a fan of doctest. Its just cleaner to write good unit tests and run it regularly.

**Comment by vu3rdd** [comment]
I took the tests from the specification wiki.

**Comment by jaseemabid** [comment]
@vu3rdd @dfordivam Before we close this, do we want doctest at all? I think its just easier and cleaner to maintain simple plain old unit tests. Otherwise, I have to find a way to integrate doctests with tasty so that they are also run on travis.

**Comment by jaseemabid** [comment]
@vu3rdd Can you enable https://travis-ci.org/vu3rdd/functorrent? You will have to login with your github account. The tests should then run on every commit as well as pull request.

**Comment by jaseemabid** [comment]
Doctests seems to be broken anyway.

```
 $ .cabal-sandbox/bin/doctest src/FuncTorrent/Bencode.hs
### Failure in src/FuncTorrent/Bencode.hs:76: expression `parse bencList "Blist" (pack "l4:spam4:eggse")'
expected: Right ["spam","eggs"]
 but got: Right [Bstr "spam",Bstr "eggs"]
### Failure in src/FuncTorrent/Bencode.hs:90: expression `parse bencDict "Bdict" (pack "d3:cow3:moo4:spam4:eggse")'
expected: Right (fromList [("cow","moo"),("spam","eggs")])
 but got: Right (fromList [(Bstr "cow",Bstr "moo"),(Bstr "spam",Bstr "eggs")])
Examples: 27  Tried: 23  Errors: 0  Failures: 2
```
